; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_upload.maximum_size = 1572864
board_build.f_cpu = 240000000L
board_build.flash_freq = 120m
board_build.arduino.memory_type = dio_opi
board_build.flash_size = 16MB
upload_protocol = esptool
monitor_speed = 115200

debug_tool = esp-builtin
debug_init_break = tbreak setup


	
build_flags = 
	-DBOARD_HAS_PSRAM
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_HOR_RES=240
	-D LV_VER_RES=320


board_build.partitions=partitions.csv
